name: Michael J. McClimon
baseurl: /
permalink: /blog/:categories/:year/:month/:day/:title.html
paginate: 5
paginate_path: /blog/page:num
markdown: redcarpet
timezone: America/Indianapolis
pygments: true
redcarpet:
  extensions: [smart]
